version: '2'
services:
    meetup-app:
        image: meetup
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://meetup-postgresql:5432/meetup
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meetup-postgresql:
        extends:
            file: postgresql.yml
            service: meetup-postgresql
